version: '3'
services:
  sta:
    image: n52/sensor-things
    build:
      context: .
      dockerfile: sensor-things-api-app/Dockerfile
    ports:
      - 8081:8081
      - 1883:1883
      - 8883:8883
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/sta

  database:
    image: mdillon/postgis
    restart: on-failure
    environment:
      - POSTGRES_DB=sta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
    # For debug/show purposes!
    ports:
      - 5000:5000