
# Log Bean initiation process
debug: false
trace: false

server:
  port: 8081
#TODO: Check if this is needed. 
database:
  jpa:
    persistence-location: classpath:META-INF/persistence.xml

# Spring 
spring:
  datasource:
    platform: postgres
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sta_test
    initialization-mode: always
  jpa:
    properties:
      hibernate: 
        hbm2ddl:
          # hbm2ddl values: validate | update | create | create-drop | none
          auto: create-drop
        jdbc:
          time_zone: UTC
          # https://hibernate.atlassian.net/browse/HHH-12368
          lob.non_contextual_creation: true
        format_sql: true
        default_schema: public
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

        # disable driver's feature detection
        # see https://stackoverflow.com/questions/46493500/hibernate-with-c3p0-createclob-is-not-yet-implemented
        temp.use_jdbc_metadata_defaults: false
  jmx:
    enabled: false
        
        
# MQTT Configuration
mqtt:
  broker:
    websocket:
      enabled: false
      port: 8081
    persistence:
      enabled: false
      path: "" # Empty for default path (java "user.dir")
      filename: "52N-STA-MQTTBroker.h2"
      autosave_interval: "30"
    
# Logging
logging:
  level:
    # root: TRACE
#    org.opengis.cite: TRACE
#    org.apache.coyote.http11.Http11InputBuffer: TRACE
#    org.hibernate: INFO
#    org.hibernate.type: INFO
    org.hibernate: TRACE
#    io.moquette: TRACE
    org.n52: TRACE
    org.springframework.orm.jpa: TRACE
