# Log Bean initiation process
debug: false
trace: false

# General Server Configuration
server:
  port: 8081
  rootUrl: "http://localhost:8081/v2/"
  contextPath: "v2"

  ## Used for enabling/disabling custom 52N-STA Features
  feature:
    ## Automatically updates a FeatureOfInterest linked in Thing->properties under
    ## key "updateFOI" with new Locations of the Thing
    updateFOI: true

    ## Defines all Collections that accept POSTing via MQTT.
    ## Default (defined by standard): "Observations" only
    mqttPublishTopics: Things, Observations

# Database Configuration
database:
  jpa:
    persistence-location: classpath:META-INF/sensorthings-persistence.xml
spring:
  datasource:
    platform: postgres
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5000/sta
    initialization-mode: always
  jpa:
    properties:
      hibernate: 
        hbm2ddl:
          # hbm2ddl values: validate | update | create | create-drop | none
          auto: update
        jdbc:
          time_zone: UTC
          # https://hibernate.atlassian.net/browse/HHH-12368
          lob.non_contextual_creation: true
        format_sql: true
        default_schema: public
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        # disable driver's feature detection
        # see https://stackoverflow.com/questions/46493500/hibernate-with-c3p0-createclob-is-not-yet-implemented
        temp.use_jdbc_metadata_defaults: false
  jmx:
    enabled: false

# HTTP Configuration
http:
  cors:
    allowOrigin: "*"
    allowMethods: "POST, PUT, GET, OPTIONS, DELETE, PATCH"
    allowHeaders: "Access-Control-Allow-Headers, Content-Type, Authorization, X-Requested-With"
    maxAge: 3600

# MQTT Configuration
mqtt:
  broker:
    plaintcp:
      enabled: false
      port: 1883
    websocket:
      enabled: false
      port: 8883
    persistence:
      enabled: false
      path: "" # Empty for default path (java "user.dir")
      filename: "52N-STA-MQTTBroker.h2"
      autosave_interval: "30"
    
# Logging
logging:
  level:
     root: INFO
#    org.opengis.cite: TRACE
#    org.apache.coyote.http11.Http11InputBuffer: TRACE
#    org.hibernate: INFO
#    org.hibernate.type: INFO
#    org.hibernate: TRACE
#    io.moquette: TRACE
     org.n52: TRACE
#    org.springframework.orm.jpa: TRACE
