# Log Bean initiation process
debug: false
trace: false

# General Server Configuration
server:
  port: 8081
  ## Used for response serialization + url parsing. Must be set correctly!
  rootUrl: "http://localhost:8081/sta/"
  servlet:
    context-path: "/sta"

  ## Used for enabling/disabling custom 52N-STA Features
  feature:
    ## Automatically updates a FeatureOfInterest linked in Thing->properties under
    ## key "updateFOI" with new Locations of the Thing
    updateFOI: false

    ## Defines all Collections that accept POSTing via MQTT.
    ## Default (defined by standard): "Observations" only
    mqttPublishTopics: Observations

    ## Toggle strict checking of encodingType for Sensor Entity
    ## When true Sensor->encodingType is not validated against allowed encodingTypes defined in the Standard
    ## (currently PDF and SensorML2)
    ## Note: This only influences encodingType when SensorEntity is posted/patched directly, not when it is inserted via nested insertion inside a Datastream
    variableEncodingType: false

    ## Toggle support for isMobile Feature
    ## When true DatasetType is set to trajectory if Thing->property contains KVP '"isMobile": "true"'
    isMobile: false

    # Toggle whether this Instance should be read-only. Can be toggled separately for MQTT and HTTP
    # All MQTT Publish Messages will be dropped silently
    mqttReadOnly: false
    # All HTTP POST & PUT Requests will be dropped with a HTTP Status 405 NOT Allowed
    httpReadOnly: false

# Database Configuration
database:
  jpa:
    persistence-location: classpath:META-INF/sensorthings-persistence.xml
spring:
  datasource:
    platform: postgres
    # the db user name
    username: postgres
    # the db user password
    password: postgres
    # here 'sta' is the name of the database
    url: jdbc:postgresql://localhost:5432/sta
    initialization-mode: always
  hikari:
    connection-timeout: 20000
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 300000 
  jpa:
    openInView: false
    properties:
      hibernate:
        # the name of the schema in the database
        default_schema: public
        hbm2ddl:
          # hbm2ddl values: validate | update | create | create-drop | none
          auto: validate
          
        jdbc:
          time_zone: UTC
          # https://hibernate.atlassian.net/browse/HHH-12368
          lob.non_contextual_creation: true
        format_sql: false
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        # disable driver's feature detection
        # see https://stackoverflow.com/questions/46493500/hibernate-with-c3p0-createclob-is-not-yet-implemented
        temp.use_jdbc_metadata_defaults: false
  jmx:
    enabled: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    servlet:
      path: /

# HTTP Configuration
http:
  cors:
    allowOrigin: "*"
    allowMethods: "POST, PUT, GET, OPTIONS, DELETE, PATCH"
    allowHeaders: "Access-Control-Allow-Headers, Content-Type, Authorization, X-Requested-With"
    maxAge: 3600

# MQTT Configuration
mqtt:
  broker:
    plaintcp:
      enabled: true
      port: 1883
    websocket:
      enabled: false
      port: 8883
    persistence:
      enabled: false
      path: "" # Empty for default path (java "user.dir")
      filename: "52N-STA-MQTTBroker.h2"
      autosave_interval: "30"
    
# Logging
logging:
  file: logs/52n-sensorthings-webapp.log
  logging.file.max-history: 10
  level:
    # root: TRACE
    org.apache.coyote.http11.Http11InputBuffer: INFO
    org.n52.sta: INFO
    org.hibernate: INFO
    org.hibernate.type: INFO
    org.hibernate.SQL: INFO
    io.moquette: INFO
